noprotect 

/*     
para una fecha

- Determinar el signo zodiacal

1. Buscar el mes
2. Cada mes tiene 2 signos asociados 
3. Evaluar a que rango pertenece el dia 
*/

var dia = prompt("Ingrese el dia");
var mes = prompt("Ingrese el mes");

// Ya sabemos el mes y el dia//

if(mes == 1)
    if( dia <= 19) {
        alert("Capricornio");
    }
    if(dia >= 20) {
        alert("Acuario");
    }



if(mes == 2)
    if( dia <= 19) {
        alert("Acuario");
    }
    if(dia >= 20) {
        alert("Piscis");
    }





    if(mes == 3)
        if( dia <= 19) {
            alert("Piscis");
        }
        if(dia >= 20) {
            alert("Aries");
        }



        if(mes == 4)
            if( dia <= 19) {
                alert("Aries");
            }
            if(dia >= 20) {
                alert("Tauro");
            }



            if(mes == 5)
                if( dia <= 19) {
                    alert("Tauro");
                }
                if(dia >= 20) {
                    alert("Geminis");
                }



            if(mes == 6)
                if( dia <= 19) {
                    alert("Gemenis");
                }
                if(dia >= 20) {
                    alert("Cancer");
                }



                if(mes == 7)
                    if( dia <= 21) {
                        alert("Cancer");
                    }
                    if(dia >= 22) {
                        alert("Leo");
                    }



                    if(mes == 8)
                        if( dia <= 22) {
                            alert("Leo");
                        }
                        if(dia >= 23) {
                            alert("Virgo");
                        }



                        if(mes == 9)
                            if( dia <= 21) {
                                alert("Virgo");
                            }
                            if(dia >= 22) {
                                alert("Libra");
                            }




                            if(mes == 10)
                                if( dia <= 22) {
                                    alert("libra");
                                }
                                if(dia >= 23) {
                                    alert("Escopion");
                                }


                                if(mes == 11)
                                    if( dia <= 21) {
                                        alert("Escorpion");
                                    }
                                    if(dia >= 22) {
                                        alert("Sagitario");
                                    }



                                    if(mes == 12)
                                        if( dia <= 21) {
                                            alert("Sagitario");
                                        }
                                        if(dia >= 22) {
                                            alert("Capricornio");
                                        }


                               



